### ISSUE TITLE
TypeError: load() takes no arguments (1 given)

### ISSUE THREAD

**Issue by bolausson** [adamserafini/zaml#18]
Hej,

indeed, the default yaml loader is slow! 
Before I go ahead and start to parse strings manually, I wanted to give your lib a go!

Thanks for trying to fix this!

I was trying to replace
`yaml.load(output, Loader=CLoader)`
with
`yaml_obj = zaml.load(output)`

but got the following error:
```
Traceback (most recent call last):
  File "./glljobstat_testing.py", line 508, in <module>
    JobStatsParser().RunBEO()
  File "./glljobstat_testing.py", line 498, in RunBEO
    self.run_once_retry(HOSTS, STATSPARAM, SSHUSER, SSHKEY, SSHKEYTYPE, "stats", HOSTPARAM)
  File "./glljobstat_testing.py", line 392, in run_once_retry
    return self.run_once_ser(HOSTS, STATSPARAM, SSHUSER, SSHKEY, SSHKEYTYPE, TYPE, HOSTPARAM)
  File "./glljobstat_testing.py", line 329, in run_once_ser
    obj = self.parse_single_job_stats(data)
  File "./glljobstat_testing.py", line 225, in parse_single_job_stats
    yaml_obj = zaml.load(output)
TypeError: load() takes no arguments (1 given)
```

I installed zaml into my venv with:
`python3 -m pip install zaml`

Any suggestions on how to solve this?

Thanks a lot,
Bjoern

**Comment by melMass** [comment]
Same here
